### ISSUE TITLE
Can't flash the GSI Image into system partition

### ISSUE THREAD

**Issue by sgh858** [samsung-sm8550/device_samsung_dm3q#2]
I tried to flash various GSI Image but TWRP always reported error as in the picture:
![Screenshot_2024-01-30-12-31-19](https://github.com/samsung-sm8550/device_samsung_dm3q/assets/53802926/f2347514-678e-46ba-8959-e28995fb1e72)

The GSI Image is not big, about 2GB. The same GSI Image can be flashed in S23 Ultra using fastboot.

**Comment by Edgars-Cirulis** [comment]
hello there can you provide recovery logs in /tmp/ ?

**Comment by Edgars-Cirulis** [comment]
Closing per no response in a week.
